package org.serginho.pojo;
// Generated Aug 28, 2015 6:39:58 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Company generated by hbm2java
 */
public class Company  implements java.io.Serializable {


     private int id;
     private String name;
     private Set<Employee> employees = new HashSet<Employee>(0);

    public Company() {
    }

	
    public Company(int id) {
        this.id = id;
    }
    public Company(int id, String name, Set<Employee> employees) {
       this.id = id;
       this.name = name;
       this.employees = employees;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<Employee> getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set<Employee> employees) {
        this.employees = employees;
    }




}


